### ISSUE TITLE
Are we allowed to use this as a resource publicly? 

### ISSUE THREAD

**Issue by FxllenCode** [grilme99/grilme99.github.io#1]
Hi, sorry for the odd question!

I forked this (although I believe I moved repositories thus why the original fork is gone) and made some changes and edits to it, never finished with it though. I was hosting in using pages and on my own domain. Recently, someone brought it up to me while looking through my repo's that this was never under a license or anything, thus not giving me the permissions to do use it at all. 

I never intended it to be used as my own site (and it wasn't even complete at the time of writing) however I would just like clarification if modification is allowed or not. I don't mind if you say I can't use it (I was using it as a resource to try and get better at non-framework front-end) so if you would like for me to delete it although that's fine with me. I've private it and took it off the domain for now. 

Thanks!

**Comment by grilme99** [comment]
Hi,

Feel free to fork & modify the code to learn from or improve upon. However, just for clarification, please do not use it as your own portfolio.
